import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 20,
    backgroundColor: "#FFFFFF",
  },
  cameraWrapper: {
    borderWidth: 1,
    borderRadius: 8,
    borderColor: "#E8E8E8",
    overflow: "hidden",
    height: 240,
    backgroundColor: "#E8E8E8",
    position: "relative",
  },
  camera: {
    flex: 1,
    position: "relative",
    backgroundColor: "#F6F6F6",
    justifyContent: "flex-end",
    alignItems: "center",
    paddingBottom: 35,
  },
  btnCamera: {
    width: 60,
    height: 60,
    borderRadius: 50,
    backgroundColor: "#A3A3A3",
    alignItems: "center",
    justifyContent: "center",
  },
  btnContainer: {
    position: "absolute",
    zIndex: 100,
    justifyContent: "center",
    alignItems: "center",
    top: 90,
  },
  btn: {
    alignItems: "center",
    justifyContent: "center",
    height: 50,
    borderRadius: 100,
    marginTop: 32,
    overflow: "hidden",
  },
  btnText: {
    fontSize: 16,
    fontFamily: "Roboto-Regular",
  },
  buttonType: {
    width: 40,
    height: 40,
    borderRadius: 50,
    backgroundColor: "#A3A3A3",
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    right: 10,
    top: 10,
  },
  inputWraper: {
    position: "relative",
  },
  input: {
    height: 50,
    borderBottomColor: "#BDBDBD",
    borderBottomWidth: 1,
    fontFamily: "Roboto-Medium",
    fontSize: 16,
    color: "#212121",
  },
  text: {
    marginTop: 8,
    fontSize: 16,
    color: "#BDBDBD",
    fontFamily: "Roboto-Regular",
    marginBottom: 32,
  },
  iconLocal: {
    top: 13,
    position: "absolute",
  },
  btnDelete: {
    width: 70,
    height: 40,
    backgroundColor: "#F6F6F6",
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginTop: "auto",
  },
});
